services:
  redis-stack:
    container_name: redis-stack
    # restart: always
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      - REDIS_ARGS= --save 300 10 --save 60 10000 --requirepass ${REDIS_PASSWORD} --appendonly yes --appendfsync everysec --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - ./redis_data:/data
volumes:
  redis_data:
